spring.application.name=kata-alten
server.port=8080
#############
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#############
spring.datasource.url=jdbc:postgresql://localhost:5432/kata_alten
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.hbm2dll.create_namespaces=true
#############
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.default_schema=kata_schema
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
#############
springfox.documentation.swagger-ui.base-url=/kata-alten/swagger-ui
##############################################
#### localhost:8080/swagger-ui/index.html ####
##############################################
#########################
springdoc.packages-to-scan=com.kataalten.controller
